# FlyingGreen in brief

Welcome to the **FlyingGreen** platform, developed by EUROCONTROL's **Aviation Sustainability Unit (ASU)** in cooperation with key aviation stakeholders. '

As unique one-stop-shop, FlyingGreen supports **ECAC Member States** and the **aviation sector** in their efforts toward decarbonisation and climate change adaptation.

Our comprehensive toolkit includes the following pillars: •

-   **NetZero:** Embark on a data-driven journey toward achieving zero emissions by 2050. Explore what-if scenarios to inform strategic decisions.

-   **FuellingDecarb:** Access centralised information on transitioning from fossil to sustainable aviation fuels. Utilise our ‘green fuels’ calculator and resource hub.

-   **ClimAdapt:** Build resilience to climate change, by using our climate risk pre-screening or ECO assessment tools and repository of information on risk assessment and adaptation.

-   **DecarbFin:** Facilitating access to funding and providing good practices and tools for compliance with EU sustainability regulations.
